version: '3'

services:
  memgraph:
    image: memgraph/memgraph-mage
    container_name: memgraph
    ports:
      - "7687:7687"

  memgraphlab:
    image: memgraph/lab
    container_name: memgraphlab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph