# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import trustlevel_pb2 as trustlevel__pb2


class ServiceDefinitionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.determineBias = channel.unary_unary(
        '/trustlevel.ServiceDefinition/determineBias',
        request_serializer=trustlevel__pb2.Input.SerializeToString,
        response_deserializer=trustlevel__pb2.BiasOutput.FromString,
        )


class ServiceDefinitionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def determineBias(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServiceDefinitionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'determineBias': grpc.unary_unary_rpc_method_handler(
          servicer.determineBias,
          request_deserializer=trustlevel__pb2.Input.FromString,
          response_serializer=trustlevel__pb2.BiasOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'trustlevel.ServiceDefinition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
